Features, tools, docs and minor bug fixes.
2005-10-15  James Antill  <james@and.org>

	* src/httpd.c (http_fin_err_req): Added more errors that can go through
	FS.
	(http__policy_req): Free current req when a match-request BLCOKs a
	connection.

	* tools/Makefile.am (crond_SCRIPTS): Added cron helpers.

	* err/Makefile.am (err_DATA): Added error pages on FS.

2005-10-14  James Antill  <james@and.org>

	* src/httpd_conf_req.c (httpd__conf_req_d1): Add return code names.

2005-10-11  James Antill  <james@and.org>

	* src/opt_policy.c (opt_policy_sc_conf_parse): Don't allow copy/inherit
	from the current policy.

	* src/httpd_conf_req.c (httpd__conf_req_d1): Add 
	content-language-extension and content-type-extension (renaming
	negotiate-* to *-negotiate, with backwards compat.)

	* src/httpd_conf_req.c (httpd__meta_build_path): Add none bracketed 
	names.

	* src/conf.h (conf_parse_num_token): Allow going to a previous token.

	* src/conf.h (conf_parse_end_token): Fix bug when skipping a lower
	depth than current.

	* src/httpd_conf_main.c (httpd__match_make): Allow positions for
	matches, and ability to add after/before them. Allow stopping of the
	match. Minor opt.

	* tools/Makefile.am (toolsmaindir): Move directory.
	(toolsmain_SCRIPS): Remove extensions.
	(toolsmain_DATA): Rename scons helper module.

2005-10-09  James Antill  <james@and.org>

	* src/opt_serv.c (opt_serv__match_init_tst_d1): Allow hostname
	comparison.
	(opt_serv__conf_d1): Add dumpable.
	(opt_serv_sc_append_cwd): Don't allocate forever.

	* src/httpd_conf_main.c (httpd__conf_main_policy_http_d1): Add explicit
	"off" authentication.
	(httpd__conf_main_policy_http_d1): Move "Server:" configuration to this
	depth.

2005-10-07  James Antill  <james@and.org>

	* src/cntl.c (cntl_pipe_acpt_fds): Add error checking to PDEATHSIG
	setting.

2005-09-29  James Antill  <james@and.org>

	* src/ex_utils.h (O_NOATIME): Add O_NOATIME support, and configuration.


git-archimport-id: james@and.org--2004-code/and-httpd--main--0--patch-6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH PERL_USR_BIN_AVAIL_TRUE PERL_USR_BIN_AVAIL_FALSE TAR_PATH CHMOD_PATH PKG_CONFIG VSTR_AVAIL_TRUE VSTR_AVAIL_FALSE VSTR_CFLAGS VSTR_LDLIBS VSTR_DBG_AVAIL_TRUE VSTR_DBG_AVAIL_FALSE VSTR_DBG_CFLAGS VSTR_DBG_LDLIBS TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS DBG_VSTR_TRUE DBG_VSTR_FALSE ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH PERL_PATH PERL_USR_BIN_AVAIL_TRUE PERL_USR_BIN_AVAIL_FALSE TAR_PATH CHMOD_PATH PKG_CONFIG VSTR_AVAIL_TRUE VSTR_AVAIL_FALSE VSTR_CFLAGS VSTR_LDLIBS VSTR_DBG_AVAIL_TRUE VSTR_DBG_AVAIL_FALSE VSTR_DBG_CFLAGS VSTR_DBG_LDLIBS TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS DBG_VSTR_TRUE DBG_VSTR_FALSE LIBCAP_AVAIL_TRUE LIBCAP_AVAIL_FALSE ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1537,7 +1537,7 @@ echo "${ECHO_T}${T_MD}Initial phase:${T_ME}" >&6
 
 
 
-VERSION=0.99.2
+VERSION=0.99.3
 PACKAGE=and-httpd
 
 am__api_version="1.9"
@@ -23349,6 +23349,172 @@ fi
 
 
 
+if test "${ac_cv_header_sys_capability_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for sys/capability.h" >&5
+echo $ECHO_N "checking for sys/capability.h... $ECHO_C" >&6
+if test "${ac_cv_header_sys_capability_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sys_capability_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_capability_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking sys/capability.h usability" >&5
+echo $ECHO_N "checking sys/capability.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <sys/capability.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking sys/capability.h presence" >&5
+echo $ECHO_N "checking sys/capability.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/capability.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sys/capability.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: sys/capability.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sys/capability.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sys/capability.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: sys/capability.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: sys/capability.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sys/capability.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/capability.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: sys/capability.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for sys/capability.h" >&5
+echo $ECHO_N "checking for sys/capability.h... $ECHO_C" >&6
+if test "${ac_cv_header_sys_capability_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_sys_capability_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sys_capability_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_capability_h" >&6
+
+fi
+if test $ac_cv_header_sys_capability_h = yes; then
+
+
+if true; then
+  LIBCAP_AVAIL_TRUE=
+  LIBCAP_AVAIL_FALSE='#'
+else
+  LIBCAP_AVAIL_TRUE='#'
+  LIBCAP_AVAIL_FALSE=
+fi
+ cat >>confdefs.h <<\_ACEOF
+#define HAVE_SYS_CAPABILITY_H 1
+_ACEOF
+
+else
+
+
+if false; then
+  LIBCAP_AVAIL_TRUE=
+  LIBCAP_AVAIL_FALSE='#'
+else
+  LIBCAP_AVAIL_TRUE='#'
+  LIBCAP_AVAIL_FALSE=
+fi
+
+fi
+
+
+
 echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
 echo "$as_me:$LINENO: result: ${T_MD}Checking for types:${T_ME}" >&5
@@ -31666,7 +31832,7 @@ echo "$as_me:$LINENO: result: ${T_MD}Output Substitution:${T_ME}" >&5
 echo "${ECHO_T}${T_MD}Output Substitution:${T_ME}" >&6
 
 
-                                                                      ac_config_files="$ac_config_files Makefile Documentation/Makefile src/Makefile tools/Makefile tools/and-httpd and-httpd.spec VERSION"
+                                                                                                    ac_config_files="$ac_config_files Makefile Documentation/Makefile err/Makefile src/Makefile tools/Makefile tools/and-httpd tools/scons_and_httpd_helpers.py tools/and-httpd_gzip and-httpd.spec VERSION"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -31874,6 +32040,20 @@ if test -z "${DBG_VSTR_TRUE}" && test -z "${DBG_VSTR_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"DBG_VSTR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"DBG_VSTR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LIBCAP_AVAIL_TRUE}" && test -z "${LIBCAP_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LIBCAP_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LIBCAP_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LIBCAP_AVAIL_TRUE}" && test -z "${LIBCAP_AVAIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LIBCAP_AVAIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LIBCAP_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -32344,9 +32524,12 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "Documentation/Makefile" ) CONFIG_FILES="$CONFIG_FILES Documentation/Makefile" ;;
+  "err/Makefile" ) CONFIG_FILES="$CONFIG_FILES err/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "tools/Makefile" ) CONFIG_FILES="$CONFIG_FILES tools/Makefile" ;;
   "tools/and-httpd" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd" ;;
+  "tools/scons_and_httpd_helpers.py" ) CONFIG_FILES="$CONFIG_FILES tools/scons_and_httpd_helpers.py" ;;
+  "tools/and-httpd_gzip" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd_gzip" ;;
   "and-httpd.spec" ) CONFIG_FILES="$CONFIG_FILES and-httpd.spec" ;;
   "VERSION" ) CONFIG_FILES="$CONFIG_FILES VERSION" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -32538,6 +32721,8 @@ s,@NDEBUG_FALSE@,$NDEBUG_FALSE,;t t
 s,@WARNS@,$WARNS,;t t
 s,@DBG_VSTR_TRUE@,$DBG_VSTR_TRUE,;t t
 s,@DBG_VSTR_FALSE@,$DBG_VSTR_FALSE,;t t
+s,@LIBCAP_AVAIL_TRUE@,$LIBCAP_AVAIL_TRUE,;t t
+s,@LIBCAP_AVAIL_FALSE@,$LIBCAP_AVAIL_FALSE,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@MALLINFO_AVAIL_TRUE@,$MALLINFO_AVAIL_TRUE,;t t
 s,@MALLINFO_AVAIL_FALSE@,$MALLINFO_AVAIL_FALSE,;t t
