Auto etag, default config. Fix MD5, hex allowed in conf strings, docs
2006-08-19  James Antill  <james@and.org>

	* src/conf.c (conf_sc_conv_unesc): Add hex escaping to strings.

	* src/httpd_app.c (http_app_hdr_vstr_md5): End header ... duh!

	* src/opt.c (opt_toggle): Add yes/no to toggle.

	* src/httpd_req.c (httpd__req_etag_auto): Generate automatic ETag
	headers based on [[[device], inode], size and mtime].

	* src/and-httpd.c (POPT_TOGGLE_ARG): Toggle all policy options, when
	passed on cmd line.

2006-08-18  James Antill  <james@and.org>

	* tools/make_index.in: Move to dir_list-1.0.css.

	* tools/scons_and_httpd_helpers.py.in (init_builders): Move to 
	f_c-1.0.css.

2006-08-14  James Antill  <james@and.org>

	* tools/SConstruct-tmpl.in: Added example template file for
	autogeneration of directory indexes.

	* src/and-httpd.c (serv_def_conf): Add a default configuration, to make
	the cmd line version even more user friendly.

	* src/httpd_conf_main.h (HTTPD_CONF_DEF_SERVER_NAME): Convert to using
	PACKAGE and VERSION generic autoconf/automake vars.

	* tools/and-httpd.in: Swap /etc HC out for @sysconfdir@, for
	sysconfig/and-httpd.


git-archimport-id: james@and.org--2004-code/and-httpd--main--0--patch-34

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH BASH_PATH PERL_PATH PERL_USR_BIN_AVAIL_TRUE PERL_USR_BIN_AVAIL_FALSE TAR_PATH CHMOD_PATH PKG_CONFIG VSTR_AVAIL_TRUE VSTR_AVAIL_FALSE VSTR_CFLAGS VSTR_LDLIBS VSTR_DBG_AVAIL_TRUE VSTR_DBG_AVAIL_FALSE VSTR_DBG_CFLAGS VSTR_DBG_LDLIBS TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS TIMER_Q_DBG_AVAIL_TRUE TIMER_Q_DBG_AVAIL_FALSE TIMER_Q_DBG_CFLAGS TIMER_Q_DBG_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS DBG_VSTR_TRUE DBG_VSTR_FALSE DBG_TIMER_Q_TRUE DBG_TIMER_Q_FALSE LIBCAP_AVAIL_TRUE LIBCAP_AVAIL_FALSE ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CFLAGS CPPFLAGS LDFLAGS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL LIBTOOL_DEPS TRUE_PATH GZIP_PATH BZIP2_PATH SENDMAIL_PATH MAKE_PATH ETAGS_PATH SED_PATH BASH_PATH PERL_PATH PERL_USR_BIN_AVAIL_TRUE PERL_USR_BIN_AVAIL_FALSE TAR_PATH CHMOD_PATH SCONS_PATH PKG_CONFIG VSTR_AVAIL_TRUE VSTR_AVAIL_FALSE VSTR_CFLAGS VSTR_LDLIBS VSTR_DBG_AVAIL_TRUE VSTR_DBG_AVAIL_FALSE VSTR_DBG_CFLAGS VSTR_DBG_LDLIBS TIMER_Q_AVAIL_TRUE TIMER_Q_AVAIL_FALSE TIMER_Q_CFLAGS TIMER_Q_LDLIBS TIMER_Q_DBG_AVAIL_TRUE TIMER_Q_DBG_AVAIL_FALSE TIMER_Q_DBG_CFLAGS TIMER_Q_DBG_LDLIBS SOCKET_POLL_AVAIL_TRUE SOCKET_POLL_AVAIL_FALSE SOCKET_POLL_CFLAGS SOCKET_POLL_LDLIBS NDEBUG_TRUE NDEBUG_FALSE WARNS DBG_VSTR_TRUE DBG_VSTR_FALSE DBG_TIMER_Q_TRUE DBG_TIMER_Q_FALSE LIBCAP_AVAIL_TRUE LIBCAP_AVAIL_FALSE ALLOCA MALLINFO_AVAIL_TRUE MALLINFO_AVAIL_FALSE HAVE_LINKER_MAIN_RELOCATE_TRUE HAVE_LINKER_MAIN_RELOCATE_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20026,7 +20026,9 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-if test "x$PERL_CONFIG" = "x/usr/bin/perl" ; then
+# Needs a better test, so /my/path/bin/perl etc. works...
+if test "x$PERL_CONFIG" = "x/usr/bin/perl" -o \
+        "x$PERL_CONFIG" = "x/usr/local/bin/perl" ; then
 
 
 if false; then
@@ -20128,6 +20130,48 @@ CHMOD_PATH=$ac_cv_path_CHMOD_PATH
 if test -n "$CHMOD_PATH"; then
   echo "$as_me:$LINENO: result: $CHMOD_PATH" >&5
 echo "${ECHO_T}$CHMOD_PATH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+# Extract the first word of "scons", so it can be a program name with args.
+set dummy scons; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_SCONS_PATH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $SCONS_PATH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_SCONS_PATH="$SCONS_PATH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+as_dummy="$PATH:/usr/bin:/bin:/usr/local/bin:/usr/gnu/bin:/usr/local/gnu/bin:/opt/gnu/bin"
+for as_dir in $as_dummy
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_SCONS_PATH="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_SCONS_PATH" && ac_cv_path_SCONS_PATH="$TRUE_PATH"
+  ;;
+esac
+fi
+SCONS_PATH=$ac_cv_path_SCONS_PATH
+
+if test -n "$SCONS_PATH"; then
+  echo "$as_me:$LINENO: result: $SCONS_PATH" >&5
+echo "${ECHO_T}$SCONS_PATH" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -22569,6 +22613,152 @@ else
   LIBCAP_AVAIL_TRUE='#'
   LIBCAP_AVAIL_FALSE=
 fi
+
+fi
+
+
+
+if test "${ac_cv_header_sys_xattr_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for sys/xattr.h" >&5
+echo $ECHO_N "checking for sys/xattr.h... $ECHO_C" >&6
+if test "${ac_cv_header_sys_xattr_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sys_xattr_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_xattr_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking sys/xattr.h usability" >&5
+echo $ECHO_N "checking sys/xattr.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <sys/xattr.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking sys/xattr.h presence" >&5
+echo $ECHO_N "checking sys/xattr.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/xattr.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sys/xattr.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: sys/xattr.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sys/xattr.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sys/xattr.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: sys/xattr.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: sys/xattr.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sys/xattr.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/xattr.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: sys/xattr.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for sys/xattr.h" >&5
+echo $ECHO_N "checking for sys/xattr.h... $ECHO_C" >&6
+if test "${ac_cv_header_sys_xattr_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_sys_xattr_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_sys_xattr_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_xattr_h" >&6
+
+fi
+if test $ac_cv_header_sys_xattr_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_SYS_XATTR_H 1
+_ACEOF
 
 fi
 
@@ -31239,7 +31429,7 @@ echo "$as_me:$LINENO: result: ${T_MD}Output Substitution:${T_ME}" >&5
 echo "${ECHO_T}${T_MD}Output Substitution:${T_ME}" >&6
 
 
-                                                                                                                                                                ac_config_files="$ac_config_files Makefile conf_tmpl/Makefile Documentation/Makefile conf/Makefile err/Makefile html/Makefile src/Makefile tools/Makefile tools/and-httpd tools/and-httpd_gzip tools/and-httpd_logs tools/and-httpd_status tools/make_index tools/scons_and_httpd_helpers.py and-httpd.spec VERSION"
+                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile conf_tmpl/Makefile Documentation/Makefile conf/Makefile err/Makefile html/Makefile src/Makefile tools/Makefile tools/and-httpd tools/and-httpd_gzip tools/and-httpd_logs tools/and-httpd_status tools/and-httpd-status tools/make_index tools/scons_and_httpd_helpers.py tools/SConstruct-tmpl and-httpd.spec VERSION"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -31955,8 +32145,10 @@ do
   "tools/and-httpd_gzip" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd_gzip" ;;
   "tools/and-httpd_logs" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd_logs" ;;
   "tools/and-httpd_status" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd_status" ;;
+  "tools/and-httpd-status" ) CONFIG_FILES="$CONFIG_FILES tools/and-httpd-status" ;;
   "tools/make_index" ) CONFIG_FILES="$CONFIG_FILES tools/make_index" ;;
   "tools/scons_and_httpd_helpers.py" ) CONFIG_FILES="$CONFIG_FILES tools/scons_and_httpd_helpers.py" ;;
+  "tools/SConstruct-tmpl" ) CONFIG_FILES="$CONFIG_FILES tools/SConstruct-tmpl" ;;
   "and-httpd.spec" ) CONFIG_FILES="$CONFIG_FILES and-httpd.spec" ;;
   "VERSION" ) CONFIG_FILES="$CONFIG_FILES VERSION" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -32127,6 +32319,7 @@ s,@PERL_USR_BIN_AVAIL_TRUE@,$PERL_USR_BIN_AVAIL_TRUE,;t t
 s,@PERL_USR_BIN_AVAIL_FALSE@,$PERL_USR_BIN_AVAIL_FALSE,;t t
 s,@TAR_PATH@,$TAR_PATH,;t t
 s,@CHMOD_PATH@,$CHMOD_PATH,;t t
+s,@SCONS_PATH@,$SCONS_PATH,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@VSTR_AVAIL_TRUE@,$VSTR_AVAIL_TRUE,;t t
 s,@VSTR_AVAIL_FALSE@,$VSTR_AVAIL_FALSE,;t t
