Fixes for brent Linux/uLibc ... and mailing-list info.
2006-03-28  James Antill  <james@and.org>

	* Documentation/and-httpd.html: Add the uLibc binary and mailing lists.

	* README: Update with info. about the dependancies etc.

2006-03-17  James Antill  <james@and.org>

	* src/httpd_policy.h (HTTPD_POLICY__EI): Cleanup extern inline
	functions and work around netinet extern vars.

	* src/opt_policy.h (OPT_POLICY__EI): Cleanup extern inline
	functions and work around netinet extern vars.

	* src/and-httpd.c (PROC_CNTL_KEEPCAPS): Fix autoconf code for when
	libcap isn't present.

	* src/malloc-check.h (MALLOC_CHECK_STORE): Use seperate name, so timer_q
	can be linked statically.

	* src/malloc-check.h (MALLOC_CHECK_DECL): Don't declare anything
	external when debugging isn't enabled.

	* configure.in (socket_poll): Error if not present.
	(timer_q): Error if not present.



git-archimport-id: james@and.org--2004-code/and-httpd--main--0--patch-19

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21237,16 +21237,9 @@ fi
 
 
 else
-
-
-if false; then
-  TIMER_Q_AVAIL_TRUE=
-  TIMER_Q_AVAIL_FALSE='#'
-else
-  TIMER_Q_AVAIL_TRUE='#'
-  TIMER_Q_AVAIL_FALSE=
-fi
-
+  { { echo "$as_me:$LINENO: error: *** Timer_q is required. See http://www.and.org/timer_q/" >&5
+echo "$as_me: error: *** Timer_q is required. See http://www.and.org/timer_q/" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 if $PKG_CONFIG --atleast-version=1.0.7 timer_q-debug ; then
@@ -21293,16 +21286,9 @@ fi
 
 
 else
-
-
-if false; then
-  SOCKET_POLL_AVAIL_TRUE=
-  SOCKET_POLL_AVAIL_FALSE='#'
-else
-  SOCKET_POLL_AVAIL_TRUE='#'
-  SOCKET_POLL_AVAIL_FALSE=
-fi
-
+  { { echo "$as_me:$LINENO: error: *** Socket_poll is required. See http://www.and.org/socket_poll/" >&5
+echo "$as_me: error: *** Socket_poll is required. See http://www.and.org/socket_poll/" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 WARNS=""
@@ -32050,13 +32036,6 @@ echo "$as_me: error: conditional \"TIMER_Q_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${TIMER_Q_AVAIL_TRUE}" && test -z "${TIMER_Q_AVAIL_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"TIMER_Q_AVAIL\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"TIMER_Q_AVAIL\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${TIMER_Q_DBG_AVAIL_TRUE}" && test -z "${TIMER_Q_DBG_AVAIL_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"TIMER_Q_DBG_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -32068,13 +32047,6 @@ if test -z "${TIMER_Q_DBG_AVAIL_TRUE}" && test -z "${TIMER_Q_DBG_AVAIL_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"TIMER_Q_DBG_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"TIMER_Q_DBG_AVAIL\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${SOCKET_POLL_AVAIL_TRUE}" && test -z "${SOCKET_POLL_AVAIL_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"SOCKET_POLL_AVAIL\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"SOCKET_POLL_AVAIL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
